### PR TITLE
Fix #205 - Move Spring Data Jackson Modules from FeignClientsConfiguration to FeignAutoConfiguration

### LINKED ISSUE #205: Unable to decode Page<T> response
> Spring Boot 2.1.6
> Spring Cloud OpenFeign 2.1.2
> Java 11

Hi there!

Looking at the Spring Cloud OpenFeign source code looks like it is able to decode Page responses, but something isn't working as expected. I have the following client:

```java
@RequestMapping(method = RequestMethod.POST, value = "users/find")
Page<UserResponse> findUsers(List<Long> usersId);
```

The `users/find` endpoint returns a `org.springframework.data.domain.Page` response, which should be decoded to `Page<UserResponse>`, but instead I get this exception:

```
Type definition error: [simple type, class org.springframework.data.domain.Page];
nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException:
Cannot construct instance of `org.springframework.data.domain.Page`
```

But shouldn't this project handle this through [PageJacksonModule.java](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/PageJacksonModule.java) and [FeignClientsConfiguration.java](https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsConfiguration.java)?

The FeignClientsConfiguration is beaning the `return new PageJacksonModule()` class during application startup, and `PageJacksonModule` has the implementation that is needed to decode a response to `Page` through:

```java
delegate = new PageImpl<>(content, PageRequest.of(number, size),
    totalElements);
```

I didn't find any instructions in the documentation regarding the Page desserialization. Am I missing something?

Best regards,
Rafael Pacheco.

### PR DESCRIPTION
**Pull request by nkonev**
Fix https://github.com/spring-cloud/spring-cloud-openfeign/issues/205

@OlgaMaciaszek Could you check this PR please ?

### CODE REVIEW

**Comment by nkonev** [comment]
Any chance to be reviewed ?

File: spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java [hunk 1]
```diff
@@ -78,6 +83,18 @@ public FeignContext feignContext() {
 		return context;
 	}
 
+	@Bean
```
Comment (OlgaMaciaszek) [inline spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java:86]: Let's add `@ConditionalOnMissingBean` as well.

File: spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java [hunk 2]
```diff
@@ -78,6 +83,18 @@ public FeignContext feignContext() {
...
+	@ConditionalOnClass(name = "org.springframework.data.domain.Page")
+	public Module pageJacksonModule() {
+		return new PageJacksonModule();
+	}
+
+	@Bean
```
Comment (OlgaMaciaszek) [inline spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java:92]: Let's add `@ConditionalOnMissingBean` as well.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Hi, @nkonev Thanks for the PR. Have added some comments. Please have a look.

**Comment by nkonev** [comment]
@OlgaMaciaszek Hi, thank you, I've done.

**Comment by nkonev** [comment]
@OlgaMaciaszek Hello! Do I have any chance to be reviewed/merged ?
This change looks simple, it isn't a big refactoring.

**Comment by OlgaMaciaszek** [comment]
Hi, @nkonev Sorry, I was away. Let me have a look at it now.

**Comment by OlgaMaciaszek** [comment]
@nkonev Have done some tests on it. This does solve the issue. However, I've realised the conditional will not be enough, as users might also register their modules just with with `Module` type also we could possibly have bean naming clashes. In order to avoid any backwards compatibility issue, let's make it opt-in by adding a new property, for example, `feign.autoconfiguration.jackson.enabled` and add a `@ConditionalOnProperty` `havingValue` `true`.

**Comment by nkonev** [comment]
@OlgaMaciaszek  Thank you for reply.
Backward compatibility is pain.
I think to add it with TODO to change it in the future Spring Clod 2021 release.

File: spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java [hunk 3]
```diff
@@ -78,6 +83,22 @@ public FeignContext feignContext() {
 		return context;
 	}
 
+	@Bean
+	@ConditionalOnMissingBean(PageJacksonModule.class)
+	@ConditionalOnClass(name = "org.springframework.data.domain.Page")
+	@ConditionalOnProperty(value = "feign.autoconfiguration.jackson.enabled", havingValue = "true", matchIfMissing = true)
```
Comment (OlgaMaciaszek) [inline spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java:89]: Since we want it to be opt-in, it should be `matchIfMissing` = `false`, which probably is the default.

File: spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java [hunk 4]
```diff
@@ -78,6 +83,22 @@ public FeignContext feignContext() {
...
+	public Module pageJacksonModule() {
+		return new PageJacksonModule();
+	}
+
+	@Bean
+	@ConditionalOnMissingBean(SortJacksonModule.class)
+	@ConditionalOnClass(name = "org.springframework.data.domain.Sort")
+	@ConditionalOnProperty(value = "feign.autoconfiguration.jackson.enabled", havingValue = "true", matchIfMissing = true)
```
Comment (OlgaMaciaszek) [inline spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java:97]: Since we want it to be opt-in, it should be `matchIfMissing` = `false`, which probably is the default.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Have added comments. Please add changes. Also, please add documentation in `spring-cloud-openfeign.adoc` describing the feature and the new property.

File: spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java (hunk 3 above)
Comment (nkonev) [reply spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java:89]: So that way we will preserve old behavior, and in order to fix bug user should manually set feign.autoconfiguration.jackson.enabled=true. Is it real need to preserve old buggy behavior ?

Comment (nkonev) [reply spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java:89]: Or may be it has the meaning to do matchIfMissing=false with TODO Change in Spring Cloud 2021 ?

**Review by OlgaMaciaszek — APPROVED** [review]

File: spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java (hunk 3 above)
Comment (OlgaMaciaszek) [reply spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignAutoConfiguration.java]: We could do it in a major. Unfortunately, a major has been just released, so we need to wait for the next one.
