### PR TITLE
Handle byte[] arrays correctly.(Fixes gh-741)

### LINKED ISSUE #741: The AbstractFormWriter.isTypeOrCollection() cannot handle byte[] arrays
**Assumptions**

There is an endpoint with `byte[]` parameter. E.g. photo parameter in following snippet.
```java
// byte[] parameter
@RequestLine("POST /send_photo")
@Headers("Content-Type: multipart/form-data")
void sendPhoto (@Param("is_public") Boolean isPublic, @Param("photo") byte[] photo);
```
The `sendPhoto()` method is called.

**Issue**

The `AbstractFormWriter.isTypeOrCollection()` tries to cast the `byte[]` value into `Object[]` which leads to the _"java.lang.ClassCastException: class [B cannot be cast to class [Ljava.lang.Object; ([B and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')"_ error.

Problem is on the line 65: https://github.com/spring-cloud/spring-cloud-openfeign/blob/10ad8a0c6ea0a5b641eb31318c93055bdaf4c4f8/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/support/AbstractFormWriter.java#L63-L65

**Expected behaviour**

The method should be able to handle arrays of primitive types without casting into `Object[]`.

FYI: @darrenfoong

### PR DESCRIPTION
**Pull request by pandaapo**
Fixes #741

Make `AbstractFormWriter#isTypeOrCollection()` handle byte[] arrays correctly instead of casting byte[] to object[] directly.

### CODE REVIEW

File: spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/AbstractFormWriterTest.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+
+import org.springframework.cloud.openfeign.support.AbstractFormWriter;
+import org.springframework.http.MediaType;
+
+/**
+ * @author Wu Daifu
+ */
+public class AbstractFormWriterTest {
```
Comment (OlgaMaciaszek) [inline spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/AbstractFormWriterTest.java:30]: Please rename the test to `AbstractFormWriterTests`. Also, please remove the unnecessary `public` keyword from the class and method signatures.

File: spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/AbstractFormWriterTest.java [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+
+	@Test
+	public void testIsApplicable() {
```
Comment (OlgaMaciaszek) [inline spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/AbstractFormWriterTest.java:33]: Please rename the method to something more meaningful like `shouldCorrectlyResolveIfApplicableForCollection`.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Thanks, @pandaapo. Just some cosmetic changes are required for the test. Please see the new comments.

File: spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/AbstractFormWriterTest.java (hunk 1 above)
Comment (leopardrota) [reply spring-cloud-openfeign-core/src/test/java/org/springframework/cloud/openfeign/support/AbstractFormWriterTest.java:30]: OK. Should I modify this on the PR of `main` branch as well?

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Thanks, @pandaapo. There's a checkstyle issue (see build results). Please fix.
